Update manifests.md
hauler-dev/hauler-docs pull request #27
Opened 2024-08-24 00:21 UTC by clemenko

2024-08-24 13:07 UTC, zackbradys commented on docs/guides-references/manifests.md
> +    # example, hauler.dev/registry: will only prepend if the server reference is missing
```suggestion
    # example: platform set globally, but not observed if set per image
    # example: registry set globally, but not observed if set per image
```

2024-08-24 13:10 UTC, zackbradys commented on docs/guides-references/manifests.md
> +    # example, hauler.dev/registry: will only prepend if the server reference is missing
Please add changes to `docs/guides-references/hauler-content/images.md` as well.

2024-08-25 01:30 UTC, zackbradys requested changes
Please add the changes to the two other occurrences of these comments in `docs/guides-references/hauler-content/images.md`.

2024-08-25 01:38 UTC, clemenko commented
completed.

2024-08-25 12:19 UTC, zackbradys approved these changes
LGTM! Thanks for the updates

2024-08-25 12:19 UTC, merged